#!/bin/sh
(cd kissat; ./configure && make && cp ./build/kissat ../bin/kissat)
(cd cadical; ./configure --competition && make && cp ./build/cadical ../bin/control)
(cd drabt; ./configure.sh && make && cp drabt ../bin/drabt)
(cp ./kissat/select_aux.py ./bin/select_aux.py)
(cd cadical; ./configure --competition CXXFLAGS="-DELIMAUX" && make && cp ./build/cadical ../bin/elim)
(cd cadical; ./configure --competition CXXFLAGS="-DBRANCHAUX" && make && cp ./build/cadical ../bin/br)
(cd cadical; ./configure --competition CXXFLAGS="-DBRANCHAUX -DELIMAUX" && make && cp ./build/cadical ../bin/br-elim)
(cd cadical; ./configure --competition CXXFLAGS="-DBRANCHAUX -DUIPAUX" && make && cp ./build/cadical ../bin/br-uip)
(cd cadical; ./configure --competition CXXFLAGS="-DUIPAUX -DBRANCHAUX -DELIMAUX"&& make && cp ./build/cadical ../bin/br-elim-uip)