all:
	$(MAKE) -C "/Users/icmccorm/git/ig/kissat/build"
kissat:
	$(MAKE) -C "/Users/icmccorm/git/ig/kissat/build" kissat
tissat:
	$(MAKE) -C "/Users/icmccorm/git/ig/kissat/build" tissat
clean:
	rm -f "/Users/icmccorm/git/ig/kissat"/makefile
	-$(MAKE) -C "/Users/icmccorm/git/ig/kissat/build" clean
	rm -rf "/Users/icmccorm/git/ig/kissat/build"
coverage:
	$(MAKE) -C "/Users/icmccorm/git/ig/kissat/build" coverage
indent:
	$(MAKE) -C "/Users/icmccorm/git/ig/kissat/build" indent
test:
	$(MAKE) -C "/Users/icmccorm/git/ig/kissat/build" test
.PHONY: all clean coverage indent kissat test tissat
